# Generated by Django 5.2.16 on 2026-07-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle',
            field=models.FileField(blank=True, help_text='Upload a WebVTT subtitle file (.vtt)', null=True, upload_to='subtitles/', verbose_name='Subtitle file'),
        ),
    ]
