# Generated by Django 5.2.16 on 2026-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='converted_subtitle',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='subtitles/vtt/', verbose_name='Converted subtitle'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subtitle',
            field=models.FileField(blank=True, help_text='Upload an SRT or VTT subtitle file.', null=True, upload_to='subtitles/source/', verbose_name='Subtitle file'),
        ),
    ]
