# Generated by Django 5.2.16 on 2026-07-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_converted_subtitle_alter_movie_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Paste a Google Drive sharing link, for example: https://drive.google.com/file/d/FILE_ID/view', max_length=1000, verbose_name='Google Drive URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_path',
            field=models.CharField(blank=True, help_text='Example: E:\\Movies\\film.mp4', max_length=1000, verbose_name='Local video file path'),
        ),
    ]
