# Generated by Django 6.0.3 on 2026-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_google_drive_url_alter_movie_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_type',
            field=models.CharField(choices=[('auto', 'Automatic'), ('mp4', 'MP4'), ('hls', 'HLS (.m3u8)')], default='auto', max_length=10, verbose_name='Video type'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='Preferred for Railway. Enter a direct .mp4 URL or an HLS .m3u8 playlist URL.', max_length=2000, verbose_name='Direct MP4 or HLS URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Transitional option. Direct MP4/HLS hosting is more reliable for seeking, mobile playback, and high traffic.', max_length=1000, verbose_name='Google Drive sharing URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_path',
            field=models.CharField(blank=True, help_text='Local development only. Example: E:\\Movies\\film.mp4', max_length=1000, verbose_name='Local video file path'),
        ),
    ]
